version: '3'

services:
  mongo:
    image: mongo:3.4.19-jessie
    container_name: ca-mongo
    volumes:
      - ./db:/data/db
    logging:
      driver: none
  idxMongo:
    image: mongo:3.4.19-jessie
    container_name: ca-idx
    logging:
      driver: none
    links:
      - mongo
    volumes:
      - ./config:/config
    command:
      - /config/run_idx.sh
    depends_on:
      - mongo
  bindaas:
    build: "./Deps/Bindaas/"
    depends_on:
      - "mongo"
    container_name: ca-data
    logging:
      driver: none
    volumes:
      - ./config/bindaas_projects/:/root/bindaas/bin/projects/
      - ./config/bindaas.config.json:/root/bindaas/bin/bindaas.config.json
  iip:
    build: "https://github.com/camicroscope/iipImage.git#develop"
    container_name: ca-iip
    volumes:
      - ./images/:/data/images/
  viewer:
    build: "https://github.com/camicroscope/caMicroscope.git#develop"
    container_name: ca-front
    logging:
      driver: none
  elevate:
    build: "https://github.com/camicroscope/Security.git#develop"
    container_name: ca-security
    logging:
      driver: none
    ports: ["4010:4010"]
    volumes:
      - ./config/routes.json:/root/src/routes.json
      - ./jwt_keys/:/keys/
  pathdb:
    build: "https://github.com/SBU-BMI/PathDB.git#master"
    container_name: ca-pathdb
    ports: ["8887:80"]
    volumes:
      - ./images/:/data/images/
      - ./jwt_keys/:/keys/
      - ./config:/config
    command:
      - /config/pathdb_pre.sh
